-- Generated by Matugen
-- Template: ~/.config/matugen/templates/nvim-base16.lua
-- Output:   ~/.config/nvim/colors/matugen.lua
-- RRethy/nvim-base16 requires "#rrggbb" format → use hex (NOT hex_stripped)

require("base16-colorscheme").setup({
	base00 = "#1a1110",
	base01 = "#140c0b",
	base02 = "#231918",
	base03 = "#534341",
	base04 = "#d8c2be",
	base05 = "#f1dfdc",
	base06 = "#392e2c",
	base07 = "#423735",
	base08 = "#dec48c",
	base09 = "#dec48c",
	base0A = "#e7bdb6",
	base0B = "#ffb4a8",
	base0C = "#564419",
	base0D = "#73342a",
	base0E = "#5d3f3a",
	base0F = "#e7bdb6",
})

-- ── Transparent Background ────────────────────────────────────────────────────
local transparent_groups = {
	"Normal",
	"NormalNC",
	"NormalFloat",
	"SignColumn",
	"FoldColumn",
	"StatusLine",
	"StatusLineNC",
	"TabLine",
	"TabLineFill",
	"TabLineSel",
	"WinBar",
	"WinBarNC",
	"LineNr",
	"CursorLineNr",
	"EndOfBuffer",
	"Pmenu",
	"PmenuSbar",
	"NeoTreeNormal",
	"NeoTreeNormalNC",
	"TelescopeNormal",
	"TelescopeBorder",
	"WhichKeyFloat",
	"NotifyBackground",
}

local function set_hl_multiple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

set_hl_multiple(transparent_groups, { bg = "NONE", ctermbg = "NONE" })

-- ── Custom Highlight Overrides ────────────────────────────────────────────────
-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#73342a",
	fg = "#ffdad4",
})

-- Strings
set_hl_multiple({ "String", "TSString", "@string" }, {
	fg = "#dec48c",
})

-- Comments
set_hl_multiple({ "TSComment", "Comment", "@comment" }, {
	fg = "#a08c89",
	italic = true,
})

-- Methods
set_hl_multiple({ "TSMethod", "Method", "@function.method", "@function.method.call" }, {
	fg = "#dec48c",
})

-- Functions
set_hl_multiple({ "TSFunction", "Function", "@function", "@function.call" }, {
	fg = "#e7bdb6",
})

-- Keywords
set_hl_multiple({
	"Keyword",
	"TSKeyword",
	"TSKeywordFunction",
	"TSRepeat",
	"@keyword",
	"@keyword.function",
	"@keyword.return",
	"@keyword.conditional",
	"@keyword.repeat",
}, {
	fg = "#904b40",
	italic = true,
})

-- Float border visible on transparent bg
vim.api.nvim_set_hl(0, "FloatBorder", {
	fg = "#a08c89",
	bg = "NONE",
})

-- Cursor line subtle on transparent
vim.api.nvim_set_hl(0, "CursorLine", {
	bg = "#231918",
})
