-- Generated by Matugen
-- Template: ~/.config/matugen/templates/nvim-base16.lua
-- Output:   ~/.config/nvim/colors/matugen.lua
-- RRethy/nvim-base16 requires "#rrggbb" format → use hex (NOT hex_stripped)

require("base16-colorscheme").setup({
	base00 = "#111318",
	base01 = "#0c0e13",
	base02 = "#191c20",
	base03 = "#43474e",
	base04 = "#c4c6cf",
	base05 = "#e1e2e9",
	base06 = "#2e3035",
	base07 = "#37393e",
	base08 = "#dbbde2",
	base09 = "#dbbde2",
	base0A = "#bdc7dc",
	base0B = "#a7c8ff",
	base0C = "#553e5d",
	base0D = "#244777",
	base0E = "#3d4758",
	base0F = "#bdc7dc",
})

-- ── Transparent Background ────────────────────────────────────────────────────
local transparent_groups = {
	"Normal",
	"NormalNC",
	"NormalFloat",
	"SignColumn",
	"FoldColumn",
	"StatusLine",
	"StatusLineNC",
	"TabLine",
	"TabLineFill",
	"TabLineSel",
	"WinBar",
	"WinBarNC",
	"LineNr",
	"CursorLineNr",
	"EndOfBuffer",
	"Pmenu",
	"PmenuSbar",
	"NeoTreeNormal",
	"NeoTreeNormalNC",
	"TelescopeNormal",
	"TelescopeBorder",
	"WhichKeyFloat",
	"NotifyBackground",
}

local function set_hl_multiple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

set_hl_multiple(transparent_groups, { bg = "NONE", ctermbg = "NONE" })

-- ── Custom Highlight Overrides ────────────────────────────────────────────────
-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#244777",
	fg = "#d5e3ff",
})

-- Strings
set_hl_multiple({ "String", "TSString", "@string" }, {
	fg = "#dbbde2",
})

-- Comments
set_hl_multiple({ "TSComment", "Comment", "@comment" }, {
	fg = "#8e9199",
	italic = true,
})

-- Methods
set_hl_multiple({ "TSMethod", "Method", "@function.method", "@function.method.call" }, {
	fg = "#dbbde2",
})

-- Functions
set_hl_multiple({ "TSFunction", "Function", "@function", "@function.call" }, {
	fg = "#bdc7dc",
})

-- Keywords
set_hl_multiple({
	"Keyword",
	"TSKeyword",
	"TSKeywordFunction",
	"TSRepeat",
	"@keyword",
	"@keyword.function",
	"@keyword.return",
	"@keyword.conditional",
	"@keyword.repeat",
}, {
	fg = "#3e5f90",
	italic = true,
})

-- Float border visible on transparent bg
vim.api.nvim_set_hl(0, "FloatBorder", {
	fg = "#8e9199",
	bg = "NONE",
})

-- Cursor line subtle on transparent
vim.api.nvim_set_hl(0, "CursorLine", {
	bg = "#191c20",
})
